@host = https://progerburik-postr-zagr-backend.herokuapp.com

###

GET {{host}}/posts/seenPost/15

###

POST {{host}}/posts
Content-Type: application/json

{
    "id": 0,
    "name": "img",
    "content": "New post"
}

###

POST {{host}}/posts
Content-Type: application/json

{
    "id": 1,
    "name": "audio",
    "content": "Updated Post"
}

###

POST {{host}}/posts/2/likes

###

DELETE {{host}}/posts/2/likes

###

DELETE {{host}}/posts/2